demo:
  url: www.huangse.com
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.1.104:3306/test?characterEncoding=utf8&allocom.mysql.jdbc.DriverwMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

